spring.application.name=microservices-order-service
server.servlet.context-path=/api/v1
server.port=8083
#RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/